#!/bin/bash
set -eu

sv=$1
IS_LATEST=${2:-}
jv=$JAVA_BASE_VERSION

CIRCLE_BRANCH=${CIRCLE_BRANCH/\//-} # fix/sth => fix-sth
tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
SUFFIX="-beta"
if [ $tagName == "release" ]; then
  SUFFIX=""
fi
imageName=$CONTAINER_NAME:v$sv$SUFFIX

echo "Configuring FROM in Dockerfile with suffix=${SUFFIX}"
sed "s/\(FROM quay\.io\/redsift\/sandbox-java\:v\).*/\1${jv}${SUFFIX}/" < Dockerfile > Dockerfile.versioned

echo Building $imageName
docker build --build-arg version=$sv -t $imageName -f ./Dockerfile.versioned .


MinorV=$(echo $sv | sed "s/\(.*\)\.\(.*\)\..*/\1.\2/")
MinorV_TAG=$CONTAINER_NAME:v$MinorV$SUFFIX
echo "Tagging as $MinorV_TAG"
docker tag $imageName $MinorV_TAG

# MAJOR_VERSION=(${rv//./ })
# MV_TAG=$CONTAINER_NAME:v$MAJOR_VERSION$SUFFIX
# echo "Tagging as $MV_TAG"
# docker tag $imageName $MV_TAG

if [[ "$tagName" == "release" ]] && [[ "$IS_LATEST" == "true" ]]; then
  echo "Tagging as $CONTAINER_NAME:latest"
  docker tag $imageName $CONTAINER_NAME:latest
fi

